name: Python Github Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/check@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: ./src
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      working-directory: ./src
      run: |
        cd src
        python -m pytest addition.py
