name: Testing workflow local and global variables

on:
  push:
     branches: [main]
 
env:
  cloud: aws-cloud

jobs:
   greeting_job:
       runs-on: ubuntu-latest
       env:
         greeting: Hello
       steps:
          - name: "say hello mahi, it's friday"
            run: echo "$greeting $First_name is using $cloud"
            env:
               First_name: mahi
